= Install Alpine Linux in chroot
:script-name: alpine-chroot-install
:script-sha1: 5571ad4d17d14bb09ad23a75060f05553786e564
:gh-name: alpinelinux/{script-name}
:version: 0.12.1

ifdef::env-github[]
image:https://github.com/{gh-name}/workflows/CI/badge.svg["Build Status", link="https://github.com/{gh-name}/actions"]
endif::env-github[]

This `alpine-chroot-install` script simplifies installation of https://alpinelinux.org/[Alpine Linux] in chroot.
Optionally it also utilizes _qemu-user_ and _binfmt_ to emulate different architecture.

The main purpose of this script is to easily create Alpine environment on debian-based CI (e.g. https://travis-ci.org/[Travis CI]) and possibly emulate other architectures (e.g. ARM) on x86_64 CI server.

Installation of Alpine Linux is a matter of seconds.
When you run this script on Travis CI, it takes *only 32 seconds* to initialize VM, install Alpine into chroot including gcc build environment and execute first command!
And just 9 seconds more if you run it with armhf emulation.


== Requirements

* Linux system with common userland (Busybox or GNU coreutils)
* POSIX-sh compatible shell (e.g. Busybox ash, dash, Bash, ZSH)
* qemu-user ≥ 2.6 and binfmt, or apt-get (needed only for emulation of different architecture)

Note that QEMU older than 2.6 doesn’t support syscall `getrandom` (384 on ARM) in qemu-user which may cause trouble with Alpine v3.5 and newer.
If older version of qemu-user is detected, the script fails.


== Usage

Read documentation in link:{script-name}[{script-name}].
See link:.github/workflows/ci.yml[] for GitHub Actions example.

You can copy link:{script-name}[{script-name}] into your repository or download it on demand, e.g.:

[source, sh, subs="verbatim, attributes"]
wget https://raw.githubusercontent.com/{gh-name}/v{version}/{script-name} \
    && echo '{script-sha1}  {script-name}' | sha1sum -c \
    || exit 1


== License

This project is licensed under http://opensource.org/licenses/MIT/[MIT License].
For the full text of the license, see the link:LICENSE[LICENSE] file.
