= Install Alpine Linux in chroot
:script-name: alpine-chroot-install
:script-sha1: 5571ad4d17d14bb09ad23a75060f05553786e564
:gh-name: alpinelinux/{script-name}
:version: 0.12.1

ifdef::env-github[]
image:https://github.com/{gh-name}/workflows/CI/badge.svg["Build Status", link="https://github.com/{gh-name}/actions"]
endif::env-github[]

This `alpine-chroot-install` script simplifies installation of https://alpinelinux.org/[Alpine Linux] for testing purposes on any x86_64 Linux system using https://man7.org/linux/man-pages/man1/chroot.1.html[chroot(1)].
Optionally it also utilizes _qemu-user_ and _binfmt_ to emulate different architecture.

The main purpose of this script is to easily create Alpine environment on Ubuntu-based CI services (e.g. https://github.com/features/actions[GitHub Actions] or https://travis-ci.org/[Travis CI]) and possibly emulate other architectures (e.g. ARM) on x86_64-only CI service.

Installation of Alpine Linux is a matter of a few seconds… *5 seconds* to be more specific.
It takes just ~5 seconds to prepare a chroot, install fresh Alpine including gcc build environment and execute first command!
And it doesn’t use any prebuilt rootfs archive or image, and no Docker, of course.
All you need to install Alpine Linux is just https://github.com/alpinelinux/apk-tools[apk-tools] -- Alpine’s package manager -- which is automatically downloaded by this script.


== Requirements

* Linux system with common userland (Busybox or GNU coreutils)
* POSIX-sh compatible shell (e.g. Busybox ash, dash, Bash, ZSH)
* qemu-user ≥ 2.6 and binfmt, or apt-get (needed only for emulation of different architecture)

Note that Alpine binaries needs up-to-date version of QEMU.
If you encounter error `qemu: Unsupported syscall`, it means that your QEMU version is too old.
If you can’t upgrade QEMU (package `qemu-user-static` on Debian/Ubuntu), try an older Alpine Linux branch (option `-b`, e.g. `-b v3.11`).


== Usage

Read documentation in link:{script-name}[{script-name}].
See link:.github/workflows/ci.yml[] for GitHub Actions example.

You can copy link:{script-name}[{script-name}] into your repository or download it on demand, e.g.:

[source, sh, subs="verbatim, attributes"]
wget https://raw.githubusercontent.com/{gh-name}/v{version}/{script-name} \
    && echo '{script-sha1}  {script-name}' | sha1sum -c \
    || exit 1


== License

This project is licensed under http://opensource.org/licenses/MIT/[MIT License].
For the full text of the license, see the link:LICENSE[LICENSE] file.
