= Install Alpine Linux in chroot
:script-name: alpine-chroot-install
:script-sha1: d0067831a65c9c1dc6fff01f7450b84006e82e30
:gh-name: alpinelinux/{script-name}
:version: 0.2.1

ifdef::env-github[]
image:https://travis-ci.org/{gh-name}.svg?branch=master["Build Status", link="https://travis-ci.org/{gh-name}"]
endif::env-github[]

This `alpine-chroot-install` script simplifies installation of https://alpinelinux.org/[Alpine Linux] in chroot.
Optionally it also utilizes _qemu-user_ and _binfmt_ to emulate different architecture.

The main purpose of this script is to easily create Alpine environment on debian-based CI (e.g. https://travis-ci.org/[Travis CI]) and possibly emulate other architectures (e.g. ARM) on x86_64 CI server.

Installation of Alpine Linux is a matter of seconds.
When you run this script on Travis CI, it takes *only 32 seconds* to initialize VM, install Alpine into chroot including gcc build environment and execute first command!
And just 9 seconds more if you run it with armhf emulation.

To get some comparison, look https://github.com/vmayoral/travis_arm_test[here] how long does this take with minimal Debian.
360 seconds!
This is 9 times more.
Do you see how bloated and slow Debian is…? ;)


== Requirements

* Linux system with common userland (Busybox or GNU coreutils)
* POSIX-sh compatible shell (e.g. Busybox ash, dash, Bash, ZSH)
* qemu-user ≥ 2.6 and binfmt, or apt-get (needed only for emulation of different architecture)

Note that QEMU older than 2.6 doesn’t support syscall `getrandom` (384 on ARM) in qemu-user which may cause trouble with Alpine v3.5 and newer.
If older version of qemu-user is detected, the script tries to install newer version of `qemu-user-static` using apt-get.
If there’s no newer version in the default system’s repository, it installs `qemu-user-static` from the Ubuntu Zesty’s repository.


== Usage

Read documentation in link:{script-name}[{script-name}].
See link:.travis.yml[.travis.yml] for Travis example.

You can copy link:{script-name}[{script-name}] into your repository or download it on demand, e.g.:

[source, sh, subs="verbatim, attributes"]
wget https://raw.githubusercontent.com/{gh-name}/v{version}/{script-name} \
    && echo '{script-sha1}  {script-name}' | sha1sum -c \
    || exit 1


== License

This project is licensed under http://opensource.org/licenses/MIT/[MIT License].
For the full text of the license, see the link:LICENSE[LICENSE] file.
