name: CI
on:
  - pull_request
  - push

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        arch:
          - x86_64
          - aarch64
          - armv7
          - ppc64le
    steps:
      - uses: actions/checkout@v4

      - run: sudo ./alpine-chroot-install -a ${{ matrix.arch }}

      - run: /alpine/enter-chroot uname -a
      - run: '[[ "$(/alpine/enter-chroot uname -m)" == ${{ matrix.arch }}* ]]'
      - run: /alpine/enter-chroot env
      - run: /alpine/enter-chroot -u $USER env
      - run: sudo /alpine/enter-chroot -u $USER env
      - run: test "$(/alpine/enter-chroot printf %s! 'Hello, world')" = 'Hello, world!'
      - run: /alpine/destroy
      - run: /alpine/destroy --remove; ! test -d /alpine
